## Importing Tensorflow

In [1]:
import tensorflow as tf

## Creating a Tensor

In [2]:
string = tf.Variable("this is a string",tf.string)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.567,tf.float64)

## Rank/Degree of a tensor

### Number of dimensions involved in a tensor. The above created tensors have a singular value and thus have a rank of 0. These are also called as Scalars.

#### For creating higher ranking tensors we do the following : 

In [3]:
rank1_tensor = tf.Variable(["one","two"],tf.string) #this is a rank 1 tensor as there is only one list with some data in it
rank2_tensor = tf.Variable([["one","two"],["three","four"]],tf.string) #this is a rank 2 tensor as there are 2 lists inside one main list

##### The ranking of a tensor in python is determined by the deepest level of list nesting.

---

##### To determine the **rank** of a tensor we use the following method

In [4]:
print(tf.rank(rank2_tensor))
print(tf.rank(rank1_tensor))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


---

## Shape of Tensors

Shape of a tensor is the amount of elements that exist in each dimension.Tensorflow will try to determine the shape of a tensor but sometimes it may be unknown

In [5]:
#in each shape, the first value refers to the number of lists/dimensions in in the tensor, and the second value refers to the number of elements in that dimension => this is for rank 2 tensors only.

print(rank2_tensor.shape) #prints (2,2) => 2 lists with 2 elements each in a list
print(rank1_tensor.shape) #prints 2 => 1 list with 2 elements in a list
print(tf.Variable([["one","two"],["three","four"],["five","six"]],tf.string).shape) #prints (3,2) => 3 lists each with 2 elements
print(tf.Variable([["one","two","three"],["four","five","six"]],tf.string).shape) #prints (2,3) => 2 lists each with 3 elements

(2, 2)
(2,)
(3, 2)
(2, 3)


---

## Changing Shape of a tensor

The number of elements of a tensor is the product of the sizes of all its shapes.There are often many shapes that have the same number of elements, making it convenient to be able to change the shape of the tensor. For example : 

In [6]:
tensor1 = tf.ones([1,2,3]) #tf.ones() creates a shape [1,2,3] tensor full of 1s
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor2,[3,-1]) # -1 tells the tensor to calculate the size of the dimension at that place. In this case, the resulting shape will be [3,2]


#NOTE:
#The number of elements in the reshaped tensor MUST match the number in the original

In [7]:
print("Tensor 1 : \n",tensor1)
print("---------------------")
print("Tensor 2 : \n",tensor2)
print("---------------------")
print("Tensor 3 : \n",tensor3)

Tensor 1 : 
 tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
---------------------
Tensor 2 : 
 tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
---------------------
Tensor 3 : 
 tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


---

## Types of Tensors

There are mainly 4 types of tensors : 
- Variable
- Constant
- Placeholder
- SparseTensor

With the exception of **Variable** , all of the remaining tensors are immutable, meaning their value may not change during execution.

---

## Evalutaing Tensors

Since tensors represent a partially complete computation we will sometimes need to run a **session** to evaluate the tensor

The simplest way to evaluate a tensor is : 

In [8]:
tensor = tf.constant(5.0) #dummy variable
with tf.compat.v1.Session() as sess:
    tensor.numpy() #Earlier tensor.eval() was used but the current versions have been changed to tensor.numpy()